apiVersion: v1
kind: ConfigMap
metadata:
  name: data-service-platform-config
  namespace: data-platform
data:
  MYSQL_HOST: mysql.data-platform.svc.cluster.local
  MYSQL_PORT: "3306"
  REDIS_HOST: redis.data-platform.svc.cluster.local
  REDIS_PORT: "6379"
  DATA_SERVICE_CIRCUIT_REDIS_ENABLED: "true"
  DATA_SERVICE_RATE_LIMIT_REDIS_ENABLED: "true"
  DATA_SERVICE_GLOBAL_MAX_CONCURRENT_PER_API: "60"
  DATA_SERVICE_CONCURRENCY_LEASE_DURATION: 30s
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces
