apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-service-platform
  namespace: data-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - data-service.example.com
      secretName: data-service-platform-tls
  rules:
    - host: data-service.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: data-service-platform-web
                port:
                  name: http
